services:
  db:
    image: library/postgres:16
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: cuteguard
      POSTGRES_PASSWORD: cuteguard
      POSTGRES_DB: cuteguard
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready'" ]
      interval: 1s
      timeout: 3s
      retries: 15
  bookofaifosi:
    image: aifosi/cuteguard:latest
    user: root
    restart: "unless-stopped"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOSTNAME: "db"
    volumes:
      - "./src/main/resources/application.conf:/opt/docker/conf/application.conf"