services:
  bookofaifosi:
    image: aifosi/cuteguard:latest
    user: root
    restart: "unless-stopped"
    volumes:
      - "./src/main/resources/application.conf:/opt/docker/conf/application.conf"